/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5ys2fe6n7rc75mpkiufly5yzqe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zlo55nr3wfh5jppefmyjku5zji",
    "aws_content_delivery_bucket": "buildopscodingquiz-20201012183056-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://buildopscodingquiz-20201012183056-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
